/**
 * Events for the communication between the main and the render processes
 */
export default {
  FILE_SELECT_PROMPT: 'FILE_SELECT_PROMPT',
  FILE_SELECT_RESPONSE: 'FILE_SELECT_RESPONSE',

  FILE_OPEN_PROMPT: 'FILE_OPEN_PROMPT',
  FILE_OPEN_RESPONSE: 'FILE_OPEN_RESPONSE',

  DIRECTORY_OPEN_PROMPT: 'DIRECTORY_OPEN_PROMPT',
  DIRECTORY_OPEN_RESPONSE: 'DIRECTORY_OPEN_RESPONSE',

  SERVER_START_PROMPT: 'SERVER_START_PROMPT',
  SERVER_STOP_PROMPT: 'SERVER_STOP_PROMPT',
  SERVER_START_RESPONSE: 'SERVER_START_RESPONSE',
  SERVER_STOP_RESPONSE: 'SERVER_STOP_RESPONSE',

  SERVER_ON_PROXY_RESPONSE: 'SERVER_ON_PROXY_RESPONSE',
  SERVER_ON_MOCK_RESPONSE: 'SERVER_ON_MOCK_RESPONSE',
};
